version: '3.8'

services:
  im-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - ENV=production
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - MAX_FILE_SIZE=10485760
      - UPLOAD_DIR=uploads/
    volumes:
      - ./uploads:/root/uploads
      - ./logs:/var/log/im-demo
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - im-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - im-network
    sysctls:
      - net.core.somaxconn=65535
    ulimits:
      memlock: -1

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - im-server
    restart: unless-stopped
    networks:
      - im-network

volumes:
  redis_data:
    driver: local

networks:
  im-network:
    driver: bridge 